"""Runtime-agnostic red/blue pipeline functions.

This is the single implementation that backs both:
- the Python reference orchestrator (scenarios/run_kill_chain.py)
- the MCP server (phantom_secops/mcp/server.py)

Everything here is a pure function over plain dicts — no docker, no LLM,
no MCP. The thin wrappers in tools/ shell into docker; the LLM provider in
phantom_secops/llm/ (Phase 3) generates prose. Both are kept out of this
module so it stays trivially testable.

Function names match the public MCP tool names from docs/MCP-INTERFACE.md.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol
from urllib.parse import unquote

REPO_ROOT = Path(__file__).resolve().parent.parent
MOCKS_DIR = REPO_ROOT / "lab" / "mocks"
LAB_LOG_DIR = REPO_ROOT / "reports" / "lab-logs"


class _ProseProvider(Protocol):
    """Structural duck-type for phantom_secops.llm.LLMProvider.

    Declared here to keep core.py free of an llm/ import cycle.
    """

    name: str

    def generate_prose(self, system: str, user: str, max_tokens: int = 1024) -> str: ...


# ─── Red pipeline ────────────────────────────────────────────────────────

def run_recon(target: str, mock: bool = False) -> dict[str, Any]:
    """Recon a lab host. In mock mode, returns canned data; in live mode,
    delegates to tools.nmap_runner (which shells into the attacker container).
    """
    if mock:
        return json.loads((MOCKS_DIR / "recon-juice-shop.json").read_text(encoding="utf-8"))
    # Lazy import: tools/ requires docker, not needed in mock mode.
    from tools import nmap_runner  # noqa: PLC0415
    return nmap_runner.run(target)


def run_vuln_scan(target: str, recon: dict[str, Any], mock: bool = False) -> dict[str, Any]:
    """Vuln scan a lab target using nuclei. Mock mode returns canned findings."""
    _ = recon  # live mode reads recon.open_ports to pick HTTP ports
    if mock:
        return json.loads((MOCKS_DIR / "vuln-scan-juice-shop.json").read_text(encoding="utf-8"))
    return {"target": target, "findings": []}


def suggest_exploit_prose(
    findings: list[dict[str, Any]],
    use_llm: bool = False,
    provider: _ProseProvider | None = None,
) -> dict[str, Any]:
    """Generate text-only exploit explanations from vuln-scan findings.

    INVARIANT: never returns runnable payloads. The output schema includes
    `has_runnable_poc: false` which is asserted by tests/test_no_runnable_poc.py.

    When `use_llm=True` and a provider is supplied (or env-var-selected at
    callsite), each finding's prose is generated by the provider and validated
    against the same forbidden-pattern set used by tests. If validation fails
    or the provider returns empty, falls back to the deterministic template.
    """
    if not findings:
        return {"markdown": "_No vulnerabilities flagged by the scan._\n",
                "has_runnable_poc": False}

    out = ["# Exploit Suggestions\n"]
    for f in findings:
        out.append(f"## {f.get('id', 'unknown')} — {f.get('title', '(no title)')}\n")
        cve = f.get("cve")
        if cve:
            out.append(f"**CVE:** {cve}")
        out.append(f"**Severity:** {f.get('severity', 'unknown')}\n")
        out.append(_finding_prose(f, use_llm=use_llm, provider=provider))
        out.append("")
    return {"markdown": "\n".join(out), "has_runnable_poc": False}


def _finding_prose(
    f: dict[str, Any],
    use_llm: bool,
    provider: _ProseProvider | None,
) -> str:
    template_text = _exploit_prose(f)
    if not use_llm or provider is None:
        return template_text

    # Lazy-import to avoid a hard dependency for the no-LLM path.
    from phantom_secops.mcp import safety  # noqa: PLC0415

    system = (
        "You are writing a prose-only security finding explanation. "
        "RULES: no shell commands, no curl/wget/sudo lines, no payload strings, "
        "no code fences with bash/sh/shell. Mitigation guidance is welcome. "
        "Plain prose only. Reference public CVE pages by number, never by URL "
        "containing exploit code."
    )
    user = json.dumps({
        "id": f.get("id"),
        "cve": f.get("cve"),
        "severity": f.get("severity"),
        "title": f.get("title"),
        "evidence": f.get("evidence"),
    }, ensure_ascii=False)

    generated = provider.generate_prose(system, user, max_tokens=400)
    if generated and safety.is_safe_prose(generated):
        return generated
    # Fallback: provider unreachable / returned forbidden patterns / empty.
    return template_text


def _exploit_prose(f: dict[str, Any]) -> str:
    """Prose only. No runnable exploits, ever."""
    sev = f.get("severity", "info")
    title = f.get("title", "")
    if "jquery" in title.lower() or "CVE-2020-11023" in (f.get("cve") or ""):
        return ("This vulnerability allows DOM-based XSS via malformed `<option>` "
                "tags processed by `htmlPrefilter`. Public references describe the "
                "exploitation path; this report does not include a runnable payload. "
                "**Mitigation:** upgrade jQuery to >=3.5.")
    if "admin" in title.lower():
        return ("Administrative interface reachable without network-layer auth. "
                "**Mitigation:** require auth on `/administration` routes or remove "
                "from production builds.")
    if sev == "low":
        return "Likely false-positive. Flagged for traceability only."
    return "See public CVE reference for exploitation details. No POC included."


# ─── Blue pipeline ───────────────────────────────────────────────────────

_LOG_PATTERNS: list[tuple[str, str, str]] = [
    ("traversal",  r"(\.\./|\.\.\\|/etc/passwd)",                              "high"),
    ("sqli",       r"(\bunion\b.*\bselect\b|\bor\s+1\s*=\s*1\b|\bsleep\s*\(\d)", "high"),
    ("xss",        r"(<script|onerror\s*=|javascript:)",                      "medium"),
    ("admin_path", r"/(administration|admin|wp-admin|\.git/|\.env|server-status)", "medium"),
    ("scanner",    r"(nikto|nmap|sqlmap|nuclei|burpsuite|wpscan)",            "low"),
]


def scan_logs_for_anomalies(
    source: str = "lab_logs",
    log_path: str | Path | None = None,
) -> dict[str, Any]:
    """Pattern-match access logs to produce raw alerts.

    URL-decodes each line before pattern-matching so injection payloads
    survive the URL encoding scanners use to slip past naive WAFs.
    """
    if log_path is not None:
        path = Path(log_path)
    elif source == "mock":
        path = MOCKS_DIR / "attack-log.txt"
    else:
        path = LAB_LOG_DIR / "juice-shop.log"

    if not path.exists():
        return {"alerts": [], "source": str(path)}

    alerts: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        decoded = unquote(line)
        for category, pat, sev in _LOG_PATTERNS:
            if re.search(pat, decoded, re.I):
                ip_m = re.match(r"^(\d{1,3}(?:\.\d{1,3}){3})", line)
                alerts.append({
                    "ts": datetime.now(timezone.utc).isoformat(),
                    "source_ip": ip_m.group(1) if ip_m else "unknown",
                    "asset": path.stem,
                    "category": category,
                    "evidence": line[:200],
                    "severity_hint": sev,
                })
                break  # one alert per line
    return {"alerts": alerts, "source": str(path)}


def triage_alerts(alerts: list[dict[str, Any]]) -> dict[str, Any]:
    """Group raw alerts by (source_ip, category) and assign priority."""
    groups: dict[tuple[str, str], dict[str, Any]] = {}
    for a in alerts:
        key = (a["source_ip"], a["category"])
        if key not in groups:
            groups[key] = {
                "ts": a["ts"],
                "priority": "P3",
                "asset": a["asset"],
                "summary": f"{a['category']} pattern from {a['source_ip']}",
                "count": 0,
                "evidence": [],
            }
        g = groups[key]
        g["count"] += 1
        if len(g["evidence"]) < 3:
            g["evidence"].append(a["evidence"])
        if a["severity_hint"] == "high":
            g["priority"] = "P1" if g["count"] >= 2 else "P2"
        elif a["severity_hint"] == "medium":
            if g["priority"] == "P3":
                g["priority"] = "P2"
    return {"triaged": list(groups.values())}


def correlate_threats(triaged: list[dict[str, Any]]) -> dict[str, Any]:
    """Group triaged alerts by source actor and infer ATT&CK phases."""
    actors: dict[str, dict[str, Any]] = {}
    for t in triaged:
        ip = t["summary"].split("from ")[-1] if "from " in t["summary"] else "unknown"
        if ip not in actors:
            actors[ip] = {
                "actor": ip,
                "first_seen": t["ts"],
                "last_seen": t["ts"],
                "phases_observed": set(),
                "alert_summaries": [],
                "narrative": "",
                "confidence": "high",
            }
        a = actors[ip]
        a["alert_summaries"].append(t["summary"])
        cat = t["summary"].split(" pattern")[0]
        if cat == "scanner":
            a["phases_observed"].add("TA0043")  # Reconnaissance
        if cat in ("sqli", "xss", "traversal"):
            a["phases_observed"].add("TA0001")  # Initial Access
        if cat == "admin_path":
            a["phases_observed"].add("TA0007")  # Discovery

    out: list[dict[str, Any]] = []
    for a in actors.values():
        a["phases_observed"] = sorted(a["phases_observed"])
        cats = [s.split(" pattern")[0] for s in a["alert_summaries"]]
        bits = []
        if "scanner" in cats:
            bits.append("active port + URL enumeration")
        if any(c in cats for c in ("sqli", "xss", "traversal")):
            bits.append("attempted injection patterns against the application")
        if "admin_path" in cats:
            bits.append("probing for admin endpoints")
        a["narrative"] = (
            f"Single actor ({a['actor']}) performed: " + "; ".join(bits) + "."
        ) if bits else "Activity observed but pattern unclear."
        out.append(a)
    return {"actors": out}


# ─── Reports ─────────────────────────────────────────────────────────────

def compose_pentest_report(
    recon: dict[str, Any],
    vuln: dict[str, Any],
    exploit_suggestions_md: str,
    timeline: list[tuple[str, str]],
) -> dict[str, Any]:
    findings = vuln.get("findings", [])
    by_sev = {s: sum(1 for f in findings if f.get("severity") == s)
              for s in ("critical", "high", "medium", "low", "info")}
    md = f"""# Pentest Report — {vuln.get('target', 'unknown')} (lab)

**Engagement**: phantom-secops kill-chain demo
**Conducted**: {datetime.now(timezone.utc).isoformat()}
**Authorization**: Self-authorized, isolated lab. See ETHICS.md.

## Executive Summary

A multi-agent pipeline executed a full kill-chain in {_total_seconds(timeline):.1f}
seconds. The recon agent identified {len(recon.get('open_ports', []))} open service(s).
The vuln-scan agent matched {len(findings)} findings ({by_sev.get('high', 0)} high,
{by_sev.get('medium', 0)} medium, {by_sev.get('low', 0)} low). No exploitation was
performed.

## Recon

Open ports:
{_render_ports(recon)}

## Findings

| Severity | Count |
|---|---|
| Critical | {by_sev.get('critical', 0)} |
| High | {by_sev.get('high', 0)} |
| Medium | {by_sev.get('medium', 0)} |
| Low | {by_sev.get('low', 0)} |
| Info | {by_sev.get('info', 0)} |

## Exploit suggestions (prose only)

{exploit_suggestions_md}

## Timeline

{_render_timeline(timeline)}
"""
    return {"markdown": md, "byte_size": len(md.encode("utf-8"))}


def compose_incident_report(
    triaged: list[dict[str, Any]],
    actors: list[dict[str, Any]],
    timeline: list[tuple[str, str]],
) -> dict[str, Any]:
    p1 = sum(1 for t in triaged if t["priority"] == "P1")
    p2 = sum(1 for t in triaged if t["priority"] == "P2")
    p3 = sum(1 for t in triaged if t["priority"] == "P3")
    mttd = mttd_seconds(timeline)
    md = f"""# Incident Report — Lab observation, {datetime.now(timezone.utc).date().isoformat()}

## TL;DR

{len(actors)} actor(s) observed against the lab. Triage pipeline produced
{p1} P1, {p2} P2, {p3} P3 grouped alerts. All activity attributable to the lab
attacker container by design.

## Timeline

{_render_timeline(timeline)}

## Actors

{_render_actors(actors)}

## Triaged alerts

{_render_triage(triaged)}

## MTTD

First probe → first triaged alert in **{mttd:.1f} seconds**.
"""
    return {"markdown": md, "byte_size": len(md.encode("utf-8")), "mttd_seconds": mttd}


# ─── Renderers / metrics ─────────────────────────────────────────────────

def _render_ports(recon: dict[str, Any]) -> str:
    ports = recon.get("open_ports", [])
    if not ports:
        return "_(none)_"
    lines = ["| Port | Service | Version |", "|---|---|---|"]
    for p in ports:
        lines.append(f"| {p.get('port')} | {p.get('service', '')} | {p.get('version') or ''} |")
    return "\n".join(lines)


def _render_timeline(tl: list[tuple[str, str]]) -> str:
    lines = ["| t (s) | Event |", "|---|---|"]
    for t, label in tl:
        lines.append(f"| {t} | {label} |")
    return "\n".join(lines)


def _render_actors(actors: list[dict[str, Any]]) -> str:
    if not actors:
        return "_(none observed)_"
    lines = []
    for a in actors:
        phases = ", ".join(a["phases_observed"]) or "_unclassified_"
        lines.append(f"### {a['actor']}")
        lines.append(f"- phases: {phases}")
        lines.append(f"- confidence: {a['confidence']}")
        lines.append(f"- narrative: {a['narrative']}\n")
    return "\n".join(lines)


def _render_triage(triaged: list[dict[str, Any]]) -> str:
    if not triaged:
        return "_(none)_"
    lines = ["| Priority | Asset | Summary | Count |", "|---|---|---|---|"]
    for t in sorted(triaged, key=lambda x: x["priority"]):
        lines.append(f"| {t['priority']} | {t['asset']} | {t['summary']} | {t['count']} |")
    return "\n".join(lines)


def _total_seconds(tl: list[tuple[str, str]]) -> float:
    return float(tl[-1][0]) if tl else 0.0


def mttd_seconds(tl: list[tuple[str, str]]) -> float:
    """First red event → first blue triaged alert."""
    first_red = next((float(t) for t, lbl in tl if "red-" in lbl and "starts" in lbl), 0.0)
    first_blue_triage = next(
        (float(t) for t, lbl in tl if "alert-triage" in lbl and "→" in lbl), 0.0
    )
    return max(0.0, first_blue_triage - first_red)
